name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r18723"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: ${{ matrix.josm-revision }}
      plugin-jar-name: 'openqa'
      perform-revision-tagging: ${{ github.repository == 'JOSM/OpenQA' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' && matrix.josm-revision == 'r18724' }}
    secrets: inherit
    permissions:
      contents: write
      deployments: write
